-- SIP-SWITCH schema: structure only, no data.
-- Auto-generated by deploy tooling; do not edit by hand.
CREATE DATABASE IF NOT EXISTS `sip_switch` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `sip_switch`;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `access_gateway_policy` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `access_point_id` bigint unsigned NOT NULL,
  `gateway_id` bigint unsigned NOT NULL,
  `policy` tinyint NOT NULL COMMENT '0 允许(白名单) 1 禁止(黑名单)',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agp` (`access_point_id`,`gateway_id`),
  KEY `idx_agp_ap` (`access_point_id`),
  KEY `idx_agp_gw` (`gateway_id`),
  CONSTRAINT `fk_agp_ap` FOREIGN KEY (`access_point_id`) REFERENCES `access_point` (`id`),
  CONSTRAINT `fk_agp_gw` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='接入允许/禁止落地';

CREATE TABLE `access_point` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `auth_mode` tinyint NOT NULL DEFAULT '0' COMMENT '0 IP白名单 1 SIP注册 2 两者并存',
  `reg_username` varchar(128) DEFAULT NULL COMMENT '注册模式用户名',
  `reg_password` varchar(128) DEFAULT NULL,
  `register_host` varchar(512) DEFAULT NULL,
  `concurrent_limit` int NOT NULL DEFAULT '0' COMMENT '接入并发上限，0=不限制',
  `record_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '1 录音（R-506 可关）',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `bill_unit` int NOT NULL DEFAULT '60',
  `reg_status` smallint NOT NULL DEFAULT '0',
  `rate` decimal(10,4) DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ap_name` (`name`),
  KEY `idx_ap_business` (`business_id`),
  KEY `idx_ap_account` (`account_id`),
  CONSTRAINT `fk_ap_business` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`),
  CONSTRAINT `chk_ap_bill_unit` CHECK ((`bill_unit` >= 1)),
  CONSTRAINT `chk_ap_concurrent` CHECK ((`concurrent_limit` >= 0)),
  CONSTRAINT `chk_ap_rate` CHECK (((`rate` is null) or (`rate` > 0)))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='接入 point';

CREATE TABLE `access_whitelist` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `access_point_id` bigint unsigned NOT NULL,
  `ip` varchar(45) NOT NULL,
  `port` int unsigned DEFAULT NULL COMMENT 'NULL=不限制端口',
  `remark` varchar(256) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_aw` (`access_point_id`,`ip`,`port`),
  KEY `idx_aw_ap` (`access_point_id`),
  CONSTRAINT `fk_aw_ap` FOREIGN KEY (`access_point_id`) REFERENCES `access_point` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='接入 IP 白名单';

CREATE TABLE `account` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  -- 历史维度 customer，业务已不使用（现以 account_number 为租户标识），可空；
  -- 与 db/migrate.py:ensure_account_customer_id_nullable 保持一致
  `customer_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `balance` decimal(14,4) NOT NULL DEFAULT '0.0000' COMMENT '账户余额，二期启用',
  `currency` varchar(8) NOT NULL DEFAULT 'CNY',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1 启用 0 停用',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `rate` decimal(10,4) DEFAULT NULL,
  `account_number` varchar(4) NOT NULL,
  `credit_limit` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `min_balance` decimal(14,4) NOT NULL DEFAULT '0.0000',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_name` (`name`),
  UNIQUE KEY `uq_account_number` (`account_number`),
  KEY `idx_account_customer` (`customer_id`),
  CONSTRAINT `fk_account_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `chk_acct_no_format` CHECK (regexp_like(`account_number`,_utf8mb4'^[0-9]{4}$')),
  CONSTRAINT `chk_acct_no_len` CHECK ((length(`account_number`) = 4)),
  CONSTRAINT `chk_acct_no_range` CHECK ((cast(`account_number` as unsigned) >= 8000)),
  CONSTRAINT `chk_acct_rate` CHECK (((`rate` is null) or (`rate` > 0)))
) ENGINE=InnoDB AUTO_INCREMENT=8004 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账户（扣费主体）';

CREATE TABLE `account_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_id` bigint NOT NULL,
  `cdr_uuid` varchar(64) DEFAULT NULL,
  `type` smallint NOT NULL COMMENT '1充值 2通话扣费 3人工调整 4退款',
  `amount` decimal(14,4) NOT NULL COMMENT '正=入账 负=出账',
  `balance_after` decimal(14,4) NOT NULL,
  `remark` varchar(256) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ledger_cdr` (`cdr_uuid`),
  KEY `idx_ledger_account_time` (`account_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `business` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `concurrent_limit` int NOT NULL DEFAULT '0' COMMENT '业务并发上限，0=不限制',
  `bill_unit` int NOT NULL DEFAULT '60' COMMENT '计费单位秒，按业务配置（R-810）',
  `rate_template_id` bigint unsigned DEFAULT NULL COMMENT '收入费率模板占位，二期启用',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_business_name` (`name`),
  KEY `idx_business_account` (`account_id`),
  CONSTRAINT `fk_business_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  CONSTRAINT `chk_biz_bill_unit` CHECK ((`bill_unit` >= 1)),
  CONSTRAINT `chk_biz_concurrent` CHECK ((`concurrent_limit` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务';

CREATE TABLE `carrier` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `cost_rate_template_id` bigint unsigned DEFAULT NULL COMMENT '成本费率模板占位，二期启用',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `bill_unit` int NOT NULL DEFAULT '60',
  `cost_rate` decimal(10,4) DEFAULT NULL,
  `balance` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `currency` varchar(8) NOT NULL DEFAULT 'CNY',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_carrier_name` (`name`),
  CONSTRAINT `chk_car_bill_unit` CHECK ((`bill_unit` >= 1)),
  CONSTRAINT `chk_car_cost_rate` CHECK (((`cost_rate` is null) or (`cost_rate` > 0)))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='落地运营商';

CREATE TABLE `carrier_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `carrier_id` bigint NOT NULL,
  `cdr_uuid` varchar(64) DEFAULT NULL,
  `type` smallint NOT NULL COMMENT '1充值 2通话扣费 3人工调整 4退款',
  `amount` decimal(14,4) NOT NULL COMMENT '正=入账 负=出账',
  `balance_after` decimal(14,4) NOT NULL,
  `remark` varchar(256) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_carrier_ledger_cdr` (`cdr_uuid`),
  KEY `idx_carrier_ledger_time` (`carrier_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cdr` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(64) NOT NULL COMMENT 'FS 通话 uuid，关联录音文件名',
  `customer_id` bigint unsigned DEFAULT NULL,
  `account_id` bigint unsigned DEFAULT NULL,
  `business_id` bigint unsigned DEFAULT NULL,
  `access_point_id` bigint unsigned DEFAULT NULL,
  `gateway_id` bigint unsigned DEFAULT NULL,
  `carrier_id` bigint unsigned DEFAULT NULL,
  `caller_in` varchar(64) NOT NULL COMMENT '呼入主叫（必有值）',
  `callee_in` varchar(64) NOT NULL COMMENT '呼入被叫（必有值）',
  `caller_mid` varchar(64) DEFAULT NULL COMMENT '中间主叫（出接入point后；校验失败置空）',
  `callee_mid` varchar(64) DEFAULT NULL COMMENT '中间被叫',
  `caller_out` varchar(64) DEFAULT NULL COMMENT '呼出主叫（出落地网关后；无路由/校验失败置空）',
  `callee_out` varchar(64) DEFAULT NULL COMMENT '呼出被叫',
  `start_time` datetime(3) NOT NULL COMMENT 'INVITE 收到',
  `ring_time` datetime(3) DEFAULT NULL COMMENT '180/183 收到，无则空',
  `answer_time` datetime(3) DEFAULT NULL COMMENT '200 收到，无则空',
  `end_time` datetime(3) DEFAULT NULL COMMENT 'BYE',
  `talk_duration` int DEFAULT NULL COMMENT '通话时长秒（answer→end）',
  `bill_unit` int NOT NULL DEFAULT '60' COMMENT '计费单位秒',
  `bill_duration` int NOT NULL DEFAULT '0' COMMENT '计费时长=ceil(talk/unit)*unit',
  `hangup_cause` varchar(32) DEFAULT NULL COMMENT 'FS hangup_cause',
  `sip_code` int DEFAULT NULL COMMENT '最终 SIP 响应码',
  `sip_invite_failure_status` varchar(16) DEFAULT NULL COMMENT '入局失败码',
  `reject_reason` varchar(64) DEFAULT NULL COMMENT '拒绝原因（可扩展枚举，见 DDL说明 §二）',
  `switch_count` int NOT NULL DEFAULT '0' COMMENT '故障切换次数',
  `switch_detail` json DEFAULT NULL COMMENT '切换轨迹',
  `record_status` tinyint NOT NULL DEFAULT '0' COMMENT '0 无 1 成功 2 失败',
  `record_path` varchar(512) DEFAULT NULL COMMENT 'OSS 路径',
  `fs_node_uuid` varchar(64) DEFAULT NULL COMMENT '承载 FS 节点',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `caller_type` varchar(16) NOT NULL DEFAULT '',
  `source_ip` varchar(64) DEFAULT NULL,
  `source_port` int DEFAULT NULL,
  `dest_ip` varchar(64) DEFAULT NULL,
  `dest_port` int DEFAULT NULL,
  `hangup_direction` smallint NOT NULL DEFAULT '0',
  `cost` decimal(12,4) NOT NULL DEFAULT '0.0000',
  `rate_used` decimal(10,4) DEFAULT NULL,
  `cost_price` decimal(12,4) NOT NULL DEFAULT '0.0000',
  `cost_rate_used` decimal(10,4) DEFAULT NULL,
  `cost_bill_unit` int DEFAULT NULL,
  `profit` decimal(12,4) NOT NULL DEFAULT '0.0000',
  `billed` smallint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`start_time`),
  UNIQUE KEY `uk_cdr_uuid` (`uuid`,`start_time`),
  KEY `idx_cdr_start` (`start_time`),
  KEY `idx_cdr_created` (`created_at`),
  KEY `idx_cdr_ap` (`access_point_id`),
  KEY `idx_cdr_gw` (`gateway_id`),
  KEY `idx_cdr_business` (`business_id`),
  KEY `idx_cdr_callee` (`callee_in`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CDR 话单（PRD §7 口径）'
/*!50100 PARTITION BY RANGE (to_days(`start_time`))
(PARTITION p202609 VALUES LESS THAN (740255) ENGINE = InnoDB,
 PARTITION p202610 VALUES LESS THAN (740286) ENGINE = InnoDB,
 PARTITION p202611 VALUES LESS THAN (740316) ENGINE = InnoDB,
 PARTITION p202612 VALUES LESS THAN (740347) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */;

CREATE TABLE `customer` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customer_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户';

CREATE TABLE `fs_node` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_uuid` varchar(64) NOT NULL,
  `name` varchar(128) NOT NULL,
  `host` varchar(45) NOT NULL,
  `esl_port` int unsigned NOT NULL DEFAULT '8021',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1 健康 0 剔除',
  `last_health_time` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_node_uuid` (`node_uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='FS 集群节点';

CREATE TABLE `gateway` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `carrier_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `ip` varchar(45) NOT NULL COMMENT 'IP 或域名',
  `port` int unsigned NOT NULL DEFAULT '5060',
  `auth_type` tinyint NOT NULL DEFAULT '0' COMMENT '0 无 1 注册',
  `username` varchar(128) DEFAULT NULL,
  `password` varchar(128) DEFAULT NULL,
  `concurrent_limit` int NOT NULL DEFAULT '0' COMMENT '落地并发上限，0=不限制',
  `heartbeat_enabled` tinyint NOT NULL DEFAULT '1' COMMENT '是否启用 OPTIONS 心跳',
  `heartbeat_interval` int NOT NULL DEFAULT '10' COMMENT '心跳周期秒',
  `heartbeat_timeout` int NOT NULL DEFAULT '3' COMMENT '连续失败阈值次数',
  `heartbeat_status` tinyint NOT NULL DEFAULT '1' COMMENT '1 在线 0 剔除',
  `last_heartbeat_time` datetime(3) DEFAULT NULL,
  `switch_mode` tinyint NOT NULL DEFAULT '0' COMMENT '0 允许180/183未到跳转 1 禁止',
  `switch_timeout` int NOT NULL DEFAULT '12' COMMENT '180/183 超时窗秒',
  `switch_codes` varchar(64) NOT NULL DEFAULT '503,500,408,486' COMMENT '可跳转异常 SIP 码集',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `failover_pre_ring_only` smallint NOT NULL DEFAULT '0',
  `heartbeat_fail_count` int NOT NULL DEFAULT '0',
  `bill_unit` int NOT NULL DEFAULT '60',
  `cost_rate` decimal(10,4) DEFAULT NULL,
  `register_expire` int NOT NULL DEFAULT '600' COMMENT '注册有效期秒(下发 expire-seconds)',
  `register_retry` int NOT NULL DEFAULT '30' COMMENT '注册重试间隔秒(下发 retry-seconds)',
  `register_status` smallint NOT NULL DEFAULT '0' COMMENT '0未注册 1已注册 2注册中 3注册失败',
  `register_status_at` datetime(3) DEFAULT NULL COMMENT '注册状态最后变更时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gateway_name` (`name`),
  KEY `idx_gateway_carrier` (`carrier_id`),
  KEY `idx_gateway_heartbeat` (`heartbeat_status`),
  CONSTRAINT `fk_gateway_carrier` FOREIGN KEY (`carrier_id`) REFERENCES `carrier` (`id`),
  CONSTRAINT `chk_gw_bill_unit` CHECK ((`bill_unit` >= 1)),
  CONSTRAINT `chk_gw_concurrent` CHECK ((`concurrent_limit` >= 0)),
  CONSTRAINT `chk_gw_cost_rate` CHECK (((`cost_rate` is null) or (`cost_rate` > 0)))
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='落地网关';

CREATE TABLE `operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operator` varchar(64) NOT NULL,
  `action` varchar(32) NOT NULL COMMENT 'CREATE/UPDATE/DELETE',
  `object_type` varchar(32) NOT NULL,
  `object_id` varchar(64) DEFAULT NULL,
  `detail` json DEFAULT NULL COMMENT '变更内容',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_oplog_time` (`created_at`),
  KEY `idx_oplog_operator` (`operator`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志（不可删）';

CREATE TABLE `prefix_route` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `gateway_id` bigint unsigned NOT NULL,
  `prefix` varchar(32) NOT NULL COMMENT '被叫前缀，最长匹配优先',
  `priority` int NOT NULL DEFAULT '0' COMMENT '同前缀多落地时的优先级',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_prefix_gw` (`gateway_id`,`prefix`),
  KEY `idx_prefix` (`prefix`),
  CONSTRAINT `fk_prefix_gateway` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前缀↔落地映射';

CREATE TABLE `rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `owner_type` tinyint NOT NULL COMMENT '0 接入point 1 落地网关',
  `owner_id` bigint unsigned NOT NULL COMMENT '软引用 owner_type 对应表主键',
  `direction` tinyint NOT NULL COMMENT '0 主叫 1 被叫',
  `pattern` varchar(64) NOT NULL COMMENT '支持 * ? 占位符',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `act` smallint NOT NULL DEFAULT '1',
  `replace_to` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_rule_owner` (`owner_type`,`owner_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='主被叫限制规则';

CREATE TABLE `sip_phone` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `phone_number` varchar(64) NOT NULL,
  `password` varchar(128) NOT NULL,
  `status` smallint NOT NULL DEFAULT '0',
  `sync_interval` int NOT NULL DEFAULT '30',
  `domain` varchar(128) NOT NULL DEFAULT '',
  `description` varchar(256) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `enabled` smallint NOT NULL DEFAULT '1',
  `rate` decimal(10,4) DEFAULT NULL,
  `account_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sip_phone_number` (`phone_number`),
  KEY `idx_sip_phone_account` (`account_id`),
  CONSTRAINT `fk_sip_phone_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_phone_no_format` CHECK (regexp_like(`phone_number`,_utf8mb4'^[0-9]{8}$')),
  CONSTRAINT `chk_phone_no_len` CHECK ((length(`phone_number`) = 8)),
  CONSTRAINT `chk_phone_rate` CHECK (((`rate` is null) or (`rate` > 0)))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(128) NOT NULL,
  `role` tinyint NOT NULL DEFAULT '1' COMMENT '0 管理员 1 只读',
  `status` tinyint NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='管理端用户';

CREATE TABLE `system_setting` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(64) NOT NULL,
  `value` varchar(512) NOT NULL,
  `description` varchar(256) DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_setting_key` (`key`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统设置';
CREATE TABLE `gateway_node` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `gateway_id` bigint unsigned NOT NULL COMMENT '关联 gateway.id (仅注册型网关 auth_type=1)',
  `node_uuid` varchar(64) NOT NULL COMMENT '归属 FS 节点 fs_node.node_uuid',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gateway` (`gateway_id`),
  KEY `idx_node` (`node_uuid`),
  CONSTRAINT `fk_gn_gateway` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_gn_node` FOREIGN KEY (`node_uuid`) REFERENCES `fs_node` (`node_uuid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='网关-节点归属：仅注册型网关单选唯一归属节点；点对点网关(auth_type=0)全量下发不在此表';
SET FOREIGN_KEY_CHECKS=1;
